### PR TITLE
fix(render): Fix onload flickering and stylable optimization issues

### PR DESCRIPTION
**Pull request by tomerlichtash**
- Add theme classname in `_document` to preset it on server.
- Use local fonts instead of Google Fonts runtime request.
- Fix Stylable optimizer to allow minified classnames in production

### CODE REVIEW

**Review by imdfl — COMMENTED** [review]
I don't mind approving this PR, but imho we're well into the Concord  fallacy.
This is the result (build + start) on my machine, in chrome (slightly worse on FF):
https://www.youtube.com/watch?v=e9FnxAYMk6Q

I have no conclusive evidence, but I still believe that the styling of this site should not remain a source of pain, discussions and pain for _months_ . This is written from the perspective of ML as a product. Regarding ML as a playground for technologies, I obviously have no criticism.

**Comment by tomerlichtash** [comment]
@imdfl, the problem you see is with the font loading, not the CSS. To prove this, remove font loading from `_document.ts` and see that the onload state is fixed.

We need to resolve font loading, but this is for another PR.

**Comment by imdfl** [comment]
I think that a font _loading_ problem would be noticeable only on the initial page load. As the clip shows, the page is reflowed on subsequent loads.
This seems to be a problem of style change, involving the at least the font, after the initial render.

**Comment by tomerlichtash** [comment]
@imdfl Fixed. Take a look: https://mels-loop-7kvhe7q6c-konzepz.vercel.app/

**Review by imdfl — APPROVED** [review]
Next challenge: convert all client utility methods to async functions that access lambda services in Azure.

**Pull request merged**
